---
name: module4_task2
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'
jobs:
  job1:
    runs-on: ubuntu-22.04
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Markdownlint
        run: sudo npm install -g markdownlint-cli
      - name: Install Markdown Link Check
        run: sudo npm install -g markdown-link-check
      - run: sudo ./module4_task2/setup.sh
      - name: Install hadolint
        run: |
          wget https://github.com/hadolint/hadolint/releases/download/v2.6.0/hadolint-Linux-x86_64
          chmod +x hadolint-Linux-x86_64
          sudo mv hadolint-Linux-x86_64 /usr/local/bin/hadolint
      - name: Install container-structure-test
        run: |
          wget https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64
          chmod +x container-structure-test-linux-amd64
          sudo mv container-structure-test-linux-amd64 /usr/local/bin/container-structure-test
      - name: Lint
        run: |
          cd module4_task2
          make lint
      - name: Build
        run: |
          cd module4_task2
          make build
      - name: Run container structure tests
        run: |
          cd module4_task2
          container-structure-test test --image awesome:build --config .build/cst.yml
      - name: Run Docker tests
        run: |
          cd module4_task2
          make docker-tests
      - name: Package
        run: make package -C module4_task2
      - name: Run
        run: make run -C  module4_task2
      - name: Run Unit tests
        run: |
          cd module4_task2
          make unit-tests
      - name: Run Integration tests
        run: |
          cd module4_task2
          make integration-tests
      - name: Get DEPLOY.md contents
        id: get-md
        run: |
          CONTENT=$(cat module4_task2/DEPLOY.md)
          CONTENT="${CONTENT//'%'/'%25'}"
          CONTENT="${CONTENT//$'\n'/'%0A'}"
          CONTENT="${CONTENT//$'\r'/'%0D'}"
          echo "::set-output name=body::$CONTENT"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: module4_task2/awesome-website.zip
          tag_name: 1.0.0
          body: ${{ steps.get-md.outputs.body }}
      - name: Deploy to Netlify
        if: |
          github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: 'module4_task2/dist'
          production-branch: main
          deploy-message: 'Deploy from GitHub Actions'
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
