---
name: module3_task1
run-name: module3_task1
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
jobs:
  job1:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: ./setup.sh
      - run: make test -C module3_task1
      - run: make build -C module3_task1
      - run: make run -C module3_task1
      - run: make stop -C module3_task1
      - run: make clean -C module3_task1
