name: module3_task4
on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
jobs:
  job1:
    runs-on: ubuntu-22.04
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.17
      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.29
          working-directory: module3_task4
      - name: Install Markdownlint
        run: sudo npm install -g markdownlint-cli
      - name: Install Markdown Link Check
        run: sudo npm install -g markdown-link-check
      - run: sudo ./module3_task4/setup.sh
      - run: make test -C  module3_task4
      - run: make build -C  module3_task4
      - run: make package -C module3_task4
      - run: make run -C  module3_task4
      - run: make stop -C  module3_task4
      - run: make clean -C  module3_task4
      - name: Get DEPLOY.md contents
        id: get-md
        run: |
          CONTENT=$(cat module3_task4/DEPLOY.md)
          CONTENT="${CONTENT//'%'/'%25'}"
          CONTENT="${CONTENT//$'\n'/'%0A'}"
          CONTENT="${CONTENT//$'\r'/'%0D'}"
          echo "::set-output name=body::$CONTENT"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: module3_task4/awesome-website.zip
          tag_name: 1.0.0
          body: ${{ steps.get-md.outputs.body }}
          permissions:
          contents: write
