---
name: module4_task2
on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
jobs:
  job1:
    runs-on: ubuntu-22.04
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Markdownlint
        run: sudo npm install -g markdownlint-cli
      - name: Install Markdown Link Check
        run: sudo npm install -g markdown-link-check
      - run: sudo ./module4_task2/setup.sh
      - run: |
          wget https://github.com/hadolint/hadolint/releases/download/v2.6.0/hadolint-Linux-x86_64
          chmod +x hadolint-Linux-x86_64
          sudo mv hadolint-Linux-x86_64 /usr/local/bin/hadolint
      - run: |
          wget https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64
          chmod +x container-structure-test-linux-amd64
          sudo mv container-structure-test-linux-amd64 /usr/local/bin/container-structure-test
      - run: |
          cd module4_task2
          make lint
      - run: |
          cd module4_task2
          make build
      - run: |
          cd module4_task2
          container-structure-test test --image awesome:build --config .build/cst.yml
      - run: |
          cd module4_task2
          make docker-tests
      - run: |
          cd module4_task2
          make integration-tests
